name: vitmav45

channels:
  - defaults
  - conda-forge
  
dependencies:
  - python=3.8
  - pip
  - pandas=1.0.3
  - tensorflow
  - tensorflow-gpu
  - seaborn=0.11.1
  - scipy=1.6.1
  - scikit-learn=0.23.2
  - plotly=4.12.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - matplotlib=3.3.2
  - yaml=0.2.5
  - shap=0.37.0

  - pip:
    - pytest
    - numpy==1.18.1
    - xlrd==1.2.0
    - xgboost==1.3.3
    - tqdm==4.56.0
    - statsmodels==0.12.2
    - streamlit==0.81.0
    - som==0.2.3
    - pingouin==0.3.9
    - catboost==0.25
    - dash==1.17.0
    - dask==2021.4.0
    - distributed==2021.4.0
    - factor-analyzer==0.3.2
    - pandas-profiling==2.11.0
    - paramiko==2.7.2
    - mlflow
